services:
  postgres:
    image: postgres:16
    container_name: assignment_api
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U POSTGRES_USER -d POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  assignment_api:
    build: .
    container_name: assignment_postgres
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DATABASE_URL: "postgresql://POSTGRES_USER:POSTGRES_PASSWORD@postgres:5432/POSTGRES_DB"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
